"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "en" | "hi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Header & Navigation
    skipToContent: "Skip to main content",
    msmePortal: "MSME SAHAYAK PORTAL",
    msmeSubtitle: "Micro, Small & Medium Enterprises Support Platform",
    initiativeUnder: "an initiative under",
    allCategories: "All Categories",
    
    // Onboarding
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिंदी",
    selectRole: "Select Your Role",
    msmeOwner: "MSME Owner",
    lender: "Lender",
    next: "Next",
    back: "Back",
    submit: "Submit",
    registrationProcess: "Registration Process",
    step: "Step",
    of: "of",
    mobileVerification: "Mobile Verification",
    enterMobileOtp: "Enter your mobile number for OTP",
    mobileNumber: "Mobile Number",
    enterOtp: "Enter OTP",
    enterSixDigitOtp: "Enter 6-digit OTP",
    kycDetails: "KYC Details",
    provideIdentityDocs: "Provide your identity documents",
    aadhaarNumber: "Aadhaar Number",
    panNumber: "PAN Number",
    businessProfile: "Business Profile",
    tellAboutBusiness: "Tell us about your business",
    businessName: "Business Name",
    enterBusinessName: "Enter business name",
    businessSector: "Business Sector",
    selectSector: "Select sector",
    manufacturing: "Manufacturing",
    trading: "Trading",
    services: "Services",
    retail: "Retail",
    location: "Location",

    // Dashboard
    dashboard: "Dashboard",
    welcomeToPortal: "Welcome to MSME Sahayak Portal",
    oneStopPlatform: "Your one-stop platform for all MSME services, loans, and government schemes",
    searchGovernmentService: "Search a GOVERNMENT SERVICE",
    typeKeyword: "Type Keyword",
    advancedSearch: "Advanced Search",
    featuredSchemes: "Featured Government Schemes",
    quickServices: "Quick Services",
    applyLoan: "Apply Loan",
    uploadDocs: "Upload Docs",
    emiCalculator: "EMI Calculator",
    getHelp: "Get Help",
    businessProfileTitle: "Your Business Profile",
    creditScore: "Credit Score",
    good: "Good",
    loanEligibility: "Loan Eligibility",
    preApproved: "Pre-approved",
    profileComplete: "Profile Complete",
    almostDone: "Almost Done",
    recommendedSchemes: "Recommended Government Schemes",
    highMatch: "High Match",
    eligible: "Eligible",
    interestRate: "Interest",
    onwards: "onwards",
    guarantee: "Guarantee",
    upTo: "Up to",
    applyNow: "Apply Now",
    learnMore: "Learn More",
    latestUpdates: "Latest Updates",
    loanApproved: "Loan Approved",
    loanApprovedDesc: "Your MUDRA loan application has been approved",
    hoursAgo: "hours ago",
    documentRequired: "Document Required",
    documentRequiredDesc: "Please upload your business license",
    dayAgo: "day ago",
    newSchemeAvailable: "New Scheme Available",
    newSchemeDesc: "PM SVANidhi scheme now open for applications",
    daysAgo: "days ago",
    inFocus: "IN FOCUS",
    digitalIndia: "Digital India Initiative",
    digitalIndiaDesc: "Empowering MSMEs through digital transformation",
    atmanirbharBharat: "Atmanirbhar Bharat",
    atmanirbharDesc: "Self-reliant India through MSME growth",
    needHelp: "Need Help?",
    chatWithSahayak: "Chat with Sahayak",
    callHelpline: "Call Helpline",
    servicesFromStates: "Services from States",

    // Service Categories
    businessServices: "Business Services",
    financialServices: "Financial Services",
    supportLearning: "Support & Learning",
    businessTools: "Business Tools",
    servicesRelatedTo: "Services related to",
    quickStatistics: "Quick Statistics",
    activeMsmes: "Active MSMEs",
    loansDispersed: "Loans Disbursed",
    schemesAvailable: "Schemes Available",

    // Schemes
    pmMudraYojana: "PM MUDRA Yojana",
    pmMudraDesc: "Loans up to ₹10 lakh for micro enterprises",
    standUpIndia: "Stand-Up India",
    standUpDesc: "₹10 lakh to ₹1 crore for SC/ST/Women entrepreneurs",
    creditGuarantee: "Credit Guarantee Scheme",
    creditGuaranteeDesc: "Collateral-free loans for MSMEs",
    digitalInitiative: "Digital India Initiative",
    digitalInitiativeDesc: "Technology adoption support for MSMEs",
    pmMudraFullDesc: "Collateral-free loans up to ₹10 lakh for micro enterprises",
    creditGuaranteeFullDesc: "Collateral-free credit facility for MSMEs up to ₹2 crore",

    // Ministry Info
    ministryFinance: "M/o Finance",
    ministryMsme: "M/o MSME",
    ministryElectronics: "M/o Electronics & IT",
    services134: "134 services",
    services96: "96 services",
    services80: "80 services",
    services70: "70 services",

    // Common
    loanMarketplace: "Loan Marketplace",
    creditProfile: "Credit Profile",
    learningHub: "Learning Hub",
    notifications: "Notifications",
    smartSahayak: "Smart Sahayak",
    upcomingPayments: "Upcoming Payments",
    suggestedSchemes: "Suggested Schemes",
    growBusiness: "Grow My Business",
    preApprovedOffers: "Pre-approved Offers",
    p2pLenders: "P2P Lenders",
    invoiceFinancing: "Invoice Financing",
    loanAmount: "Loan Amount",
    tenure: "Tenure",
    profileCompleteTitle: "Profile Complete",
    uploadDocuments: "Upload Documents",
    businessToolkit: "Business Toolkit",
    orders: "Orders",
    inventory: "Inventory",
    customers: "Customers",
    invoices: "Invoices",
    analytics: "Analytics",
    videos: "Videos",
    articles: "Articles",
    caseStudies: "Case Studies",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    mobileApp: "MOBILE APP",
    googlePlay: "Google Play",
    appStore: "App Store",
  },
  hi: {
    // Header & Navigation
    skipToContent: "मुख्य सामग्री पर जाएं",
    msmePortal: "MSME सहायक पोर्टल",
    msmeSubtitle: "सूक्ष्म, लघु और मध्यम उद्यम सहायता मंच",
    initiativeUnder: "के तहत एक पहल",
    allCategories: "सभी श्रेणियां",

    // Onboarding
    selectLanguage: "भाषा चुनें",
    english: "English",
    hindi: "हिंदी",
    selectRole: "अपनी भूमिका चुनें",
    msmeOwner: "MSME मालिक",
    lender: "ऋणदाता",
    next: "आगे",
    back: "पीछे",
    submit: "जमा करें",
    registrationProcess: "पंजीकरण प्रक्रिया",
    step: "चरण",
    of: "का",
    mobileVerification: "मोबाइल सत्यापन",
    enterMobileOtp: "OTP के लिए अपना मोबाइल नंबर दर्ज करें",
    mobileNumber: "मोबाइल नंबर",
    enterOtp: "OTP दर्ज करें",
    enterSixDigitOtp: "6-अंकीय OTP दर्ज करें",
    kycDetails: "KYC विवरण",
    provideIdentityDocs: "अपने पहचान दस्तावेज़ प्रदान करें",
    aadhaarNumber: "आधार संख्या",
    panNumber: "पैन संख्या",
    businessProfile: "व्यवसाय प्रोफ़ाइल",
    tellAboutBusiness: "अपने व्यवसाय के बारे में बताएं",
    businessName: "व्यवसाय का नाम",
    enterBusinessName: "व्यवसाय का नाम दर्ज करें",
    businessSector: "व्यवसाय क्षेत्र",
    selectSector: "क्षेत्र चुनें",
    manufacturing: "विनिर्माण",
    trading: "व्यापार",
    services: "सेवाएं",
    retail: "खुदरा",
    location: "स्थान",

    // Dashboard
    dashboard: "डैशबोर्ड",
    welcomeToPortal: "MSME सहायक पोर्टल में आपका स्वागत है",
    oneStopPlatform: "सभी MSME सेवाओं, ऋणों और सरकारी योजनाओं के लिए आपका एक-स्टॉप प्लेटफॉर्म",
    searchGovernmentService: "सरकारी सेवा खोजें",
    typeKeyword: "कीवर्ड टाइप करें",
    advancedSearch: "उन्नत खोज",
    featuredSchemes: "विशेष सरकारी योजनाएं",
    quickServices: "त्वरित सेवाएं",
    applyLoan: "ऋण आवेदन",
    uploadDocs: "दस्तावेज़ अपलोड",
    emiCalculator: "EMI कैलकुलेटर",
    getHelp: "सहायता पाएं",
    businessProfileTitle: "आपकी व्यवसाय प्रोफ़ाइल",
    creditScore: "क्रेडिट स्कोर",
    good: "अच्छा",
    loanEligibility: "ऋण पात्रता",
    preApproved: "पूर्व-अनुमोदित",
    profileComplete: "प्रोफ़ाइल पूर्ण",
    almostDone: "लगभग पूर्ण",
    recommendedSchemes: "अनुशंसित सरकारी योजनाएं",
    highMatch: "उच्च मैच",
    eligible: "पात्र",
    interestRate: "ब्याज",
    onwards: "से आगे",
    guarantee: "गारंटी",
    upTo: "तक",
    applyNow: "अभी आवेदन करें",
    learnMore: "और जानें",
    latestUpdates: "नवीनतम अपडेट",
    loanApproved: "ऋण स्वीकृत",
    loanApprovedDesc: "आपका MUDRA ऋण आवेदन स्वीकृत हो गया है",
    hoursAgo: "घंटे पहले",
    documentRequired: "दस्तावेज़ आवश्यक",
    documentRequiredDesc: "कृपया अपना व्यवसाय लाइसेंस अपलोड करें",
    dayAgo: "दिन पहले",
    newSchemeAvailable: "नई योजना उपलब्ध",
    newSchemeDesc: "PM SVANidhi योजना अब आवेदन के लिए खुली है",
    daysAgo: "दिन पहले",
    inFocus: "फोकस में",
    digitalIndia: "डिजिटल इंडिया पहल",
    digitalIndiaDesc: "डिजिटल परिवर्तन के माध्यम से MSMEs को सशक्त बनाना",
    atmanirbharBharat: "आत्मनिर्भर भारत",
    atmanirbharDesc: "MSME विकास के माध्यम से आत्मनिर्भर भारत",
    needHelp: "सहायता चाहिए?",
    chatWithSahayak: "सहायक से चैट करें",
    callHelpline: "हेल्पलाइन कॉल करें",
    servicesFromStates: "राज्यों की सेवाएं",

    // Service Categories
    businessServices: "व्यवसाय सेवाएं",
    financialServices: "वित्तीय सेवाएं",
    supportLearning: "सहायता और शिक्षा",
    businessTools: "व्यवसाय उपकरण",
    servicesRelatedTo: "संबंधित सेवाएं",
    quickStatistics: "त्वरित आंकड़े",
    activeMsmes: "सक्रिय MSMEs",
    loansDispersed: "वितरित ऋण",
    schemesAvailable: "उपलब्ध योजनाएं",

    // Schemes
    pmMudraYojana: "PM मुद्रा योजना",
    pmMudraDesc: "सूक्ष्म उद्यमों के लिए ₹10 लाख तक का ऋण",
    standUpIndia: "स्टैंड-अप इंडिया",
    standUpDesc: "SC/ST/महिला उद्यमियों के लिए ₹10 लाख से ₹1 करोड़",
    creditGuarantee: "क्रेडिट गारंटी योजना",
    creditGuaranteeDesc: "MSMEs के लिए संपार्श्विक-मुक्त ऋण",
    digitalInitiative: "डिजिटल इंडिया पहल",
    digitalInitiativeDesc: "MSMEs के लिए प्रौद्योगिकी अपनाने का समर्थन",
    pmMudraFullDesc: "सूक्ष्म उद्यमों के लिए ₹10 लाख तक संपार्श्विक-मुक्त ऋण",
    creditGuaranteeFullDesc: "MSMEs के लिए ₹2 करोड़ तक संपार्श्विक-मुक्त क्रेडिट सुविधा",

    // Ministry Info
    ministryFinance: "वित्त मंत्रालय",
    ministryMsme: "MSME मंत्रालय",
    ministryElectronics: "इलेक्ट्रॉनिक्स और IT मंत्रालय",
    services134: "134 सेवाएं",
    services96: "96 सेवाएं",
    services80: "80 सेवाएं",
    services70: "70 सेवाएं",

    // Common
    loanMarketplace: "ऋण बाज़ार",
    creditProfile: "क्रेडिट प्रोफ़ाइल",
    learningHub: "शिक्षा केंद्र",
    notifications: "सूचनाएं",
    smartSahayak: "स्मार्ट सहायक",
    upcomingPayments: "आगामी भुगतान",
    suggestedSchemes: "सुझाई गई योजनाएं",
    growBusiness: "व्यवसाय बढ़ाएं",
    preApprovedOffers: "पूर्व-अनुमोदित ऑफर",
    p2pLenders: "P2P ऋणदाता",
    invoiceFinancing: "चालान वित्तपोषण",
    loanAmount: "ऋण राशि",
    tenure: "अवधि",
    profileCompleteTitle: "प्रोफ़ाइल पूर्ण",
    uploadDocuments: "दस्तावेज़ अपलोड करें",
    businessToolkit: "व्यवसाय टूलकिट",
    orders: "ऑर्डर",
    inventory: "इन्वेंटरी",
    customers: "ग्राहक",
    invoices: "चालान",
    analytics: "विश्लेषण",
    videos: "वीडियो",
    articles: "लेख",
    caseStudies: "केस स्टडी",
    save: "सेव करें",
    cancel: "रद्द करें",
    loading: "लोड हो रहा है...",
    mobileApp: "मोबाइल ऐप",
    googlePlay: "गूगल प्ले",
    appStore: "ऐप स्टोर",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["en"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
